default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>

development:
  <<: *default
  database: <%= ENV.fetch 'POSTGRES_DB', 'timetable_development' %>

test:
  <<: *default
  host: localhost
  database: <%= ENV.fetch 'POSTGRES_DB', 'timetable_test' %>

production:
  <<: *default
  database: timetable_production
  username: timetable
