default: &default
  web_domain: <%= ENV.fetch 'WEB_DOMAIN', 'localhost:3000' %>

development:
  <<: *detault
  secret_key_base: 9d8b05c41d1d88e1df663e3174ef4dec2c613aece6a3ccf844918407f5296689babe2cf086ff36add56e13148b932502bc2c3c761bb92b67f64657ba9a25f242

test:
  <<: *detault
  secret_key_base: 13192590a7cd5f358cc209e77e9d622409c031d27502c5076cc2fc85af25f8aad7d77160bf2a91a6c92142a9c0a05054fd1913f34d5c6889f8e2c30c01298952

production:
  <<: *detault
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
